/**
 * Emitters: turn the preprocessed API model into TypeScript source files.
 *
 * - Named object schemas -> interfaces via json-schema-to-typescript
 * - Named enum schemas   -> const-object + literal-union pairs (not TS enums:
 *   structural typing, erasableSyntaxOnly-safe, runtime-iterable)
 * - Method/event surface -> ApiCallDirectory / ApiJobDirectory / ApiEventDirectory
 */
import { compile } from 'json-schema-to-typescript';

import type { DefSchema, EventModel, MethodModel, Schema } from './types.mts';

type CompileInput = Parameters<typeof compile>[0];

export const HEADER = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-api-interface from a \`middlewared --dump-api\` dump.
 */
`;

const QUERY_TYPE_NAMES = ['QueryFilter', 'QueryFilterField', 'QueryFilters', 'QueryOperator', 'QueryOptions'];

const refName = (ref: string): string => ref.replace('#/definitions/', '');

const isIdentifier = (s: string): boolean => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);

const toIdentifier = (s: string): string => {
  const cleaned = s.replace(/[^A-Za-z0-9_$]+/g, '_');
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
};

const quote = (value: unknown): string => `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const literal = (value: unknown): string => (typeof value === 'string' ? quote(value) : JSON.stringify(value));

/** Enum member name from a value: 'ACTIVE DIRECTORY' -> ActiveDirectory. */
function memberName(value: unknown): string {
  const name = String(value)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((t) => (t === t.toUpperCase() ? t.toLowerCase() : t))
    .map((t) => t[0].toUpperCase() + t.slice(1))
    .join('');
  return name && isIdentifier(name) ? name : quote(value);
}

/** Shallow JSON Schema -> TypeScript type expression (refs resolve to def names). */
export function tsExpr(schema: Schema | boolean | undefined | null): string {
  if (schema === true || schema === false || schema === undefined || schema === null) return 'unknown';
  if (schema.tsType) return schema.tsType;
  if (schema.$ref) return refName(schema.$ref);
  if ('const' in schema) return literal(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map(literal).join(' | ');

  const variants = schema.anyOf ?? schema.oneOf;
  if (variants) {
    const parts = [...new Set(variants.map(tsExpr))];
    return parts.join(' | ');
  }
  if (schema.allOf?.length === 1) return tsExpr(schema.allOf[0]);

  if (Array.isArray(schema.type)) {
    return schema.type.map((t) => tsExpr({ ...schema, type: t })).join(' | ');
  }
  switch (schema.type) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': {
      if (schema.prefixItems && schema.items === false) {
        return `[${schema.prefixItems.map(tsExpr).join(', ')}]`;
      }
      const item = schema.items ? tsExpr(schema.items) : 'unknown';
      return /[|&\s]/.test(item) ? `(${item})[]` : `${item}[]`;
    }
    case 'object': {
      const props = schema.properties ?? {};
      const keys = Object.keys(props);
      if (keys.length === 0) {
        const patterns = Object.values(schema.patternProperties ?? {});
        if (patterns.length > 0) {
          return `Record<string, ${[...new Set(patterns.map(tsExpr))].join(' | ')}>`;
        }
        if (schema.additionalProperties === false) return 'Record<string, never>';
        if (typeof schema.additionalProperties === 'object' && schema.additionalProperties !== null) {
          return `Record<string, ${tsExpr(schema.additionalProperties)}>`;
        }
        return 'Record<string, unknown>';
      }
      const required = new Set(schema.required ?? []);
      const fields = keys.map((k) => {
        const key = isIdentifier(k) ? k : quote(k);
        return `${key}${required.has(k) ? '' : '?'}: ${tsExpr(props[k])}`;
      });
      return `{ ${fields.join('; ')} }`;
    }
    default: return 'unknown';
  }
}

function tsdoc(lines: (string | null | undefined)[], indent = '  '): string {
  const content = lines.filter(Boolean).flatMap((l) => String(l).split('\n'));
  if (content.length === 0) return '';
  return `${indent}/**\n${content.map((l) => `${indent} * ${l}`.trimEnd()).join('\n')}\n${indent} */\n`;
}

function methodDoc(method: MethodModel): string {
  return tsdoc([
    method.doc,
    method.roles.length ? `@roles ${method.roles.join(', ')}` : null,
    method.removedIn ? `@deprecated Removed in API version ${method.removedIn}.` : null,
  ]);
}

/**
 * Pydantic stamps a `title` on every field, and json-schema-to-typescript
 * hoists every titled subschema into a standalone named alias (Id1, Title2, …).
 * Titles are only meaningful as def names, so strip them everywhere below the
 * def root.
 */
function stripNestedTitles(node: unknown, isRoot = true): unknown {
  if (Array.isArray(node)) return node.map((n) => stripNestedTitles(n, false));
  if (node === null || typeof node !== 'object') return node;
  const source = node as Schema;
  const out: Schema = {};
  for (const [key, value] of Object.entries(source)) {
    if (key === 'title' && !isRoot) continue;
    // A $ref with siblings makes json-schema-to-typescript clone the target
    // into a suffixed duplicate (Alert1); keep such refs bare instead.
    if (source.$ref && key !== '$ref') continue;
    out[key] = stripNestedTitles(value, false);
  }
  // Closed empty objects render as the banned `{}` type; match tsExpr().
  if (out.type === 'object' && !out.$ref
    && Object.keys(out.properties ?? {}).length === 0
    && out.additionalProperties === false) {
    return { ...(out.description && { description: out.description }), tsType: 'Record<string, never>' };
  }
  return out;
}

/** "Used by: user.create (params), …" doc line, capped so hub types stay readable. */
function usedByLine(usedBy: string[] | undefined, cap = 10): string | null {
  if (!usedBy?.length) return null;
  const shown = usedBy.slice(0, cap).join(', ');
  const extra = usedBy.length > cap ? ` … and ${usedBy.length - cap} more` : '';
  return `Used by: ${shown}${extra}`;
}

/** name -> module path (relative to the emitting file) for inherited types. */
export type Externals = Map<string, string>;

function groupedImports(names: string[], externals: Externals, localPath: string): string {
  const byPath = new Map<string, string[]>();
  for (const name of names) {
    const from = externals.get(name) ?? localPath;
    byPath.set(from, [...(byPath.get(from) ?? []), name]);
  }
  return [...byPath.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, list]) => `import type {\n${list.sort().map((n) => `  ${n},`).join('\n')}\n} from '${from}';\n`)
    .join('');
}

/**
 * api-types.ts: interfaces (via json-schema-to-typescript) + const-object
 * enums. `externals` maps types declared in ancestor versions to their module
 * paths — they are imported rather than declared, keeping every shape
 * materialized exactly once across the chain.
 */
/** True for defs json-schema-to-typescript declares reliably: objects with fields. */
const isDeclarableObject = (s: Schema): boolean => s.type === 'object'
  && Object.keys(s.properties ?? {}).length > 0;

export async function emitTypes(definitions: Record<string, DefSchema>, externals: Externals = new Map()): Promise<string> {
  const objectDefs: Record<string, Schema> = {};
  const enumDefs: Record<string, Schema> = {};
  // json-schema-to-typescript silently drops top-level defs that aren't
  // field-bearing objects (arrays, empty marker models, primitives, unions),
  // so those are declared by us via tsExpr, like enums.
  const aliasDefs: Record<string, Schema> = {};
  for (const [name, def] of Object.entries(definitions)) {
    const { _kind, _usedBy, ...schema } = def;
    const usage = usedByLine(_usedBy);
    if (usage) {
      schema.description = schema.description ? `${schema.description}\n\n${usage}` : usage;
    }
    const bucket = _kind === 'enum' ? enumDefs : isDeclarableObject(schema) ? objectDefs : aliasDefs;
    bucket[name] = stripNestedTitles(schema) as Schema;
  }

  // Enum defs are emitted by us and shared defs are imported; hand
  // json-schema-to-typescript an opaque `tsType` for both so references
  // render as the bare name.
  const referencedExternal = [...collectRefs([Object.values(objectDefs), Object.values(aliasDefs)], new Set())]
    .filter((name) => externals.has(name))
    .sort();
  const jstsDefinitions: Record<string, Schema> = {
    ...objectDefs,
    ...Object.fromEntries(Object.keys(enumDefs).map((name) => [name, { tsType: name }])),
    ...Object.fromEntries(Object.keys(aliasDefs).map((name) => [name, { tsType: name }])),
    ...Object.fromEntries(referencedExternal.map((name) => [name, { tsType: name }])),
  };

  const root: Schema = {
    title: 'GeneratedRoot', type: 'object', additionalProperties: false, properties: {}, definitions: jstsDefinitions,
  };
  let interfaces = await compile(
    root as CompileInput,
    'GeneratedRoot',
    // additionalProperties intentionally not defaulted to false: pydantic
    // models set it explicitly; bare `dict` fields should stay open records.
    { bannerComment: '', unreachableDefinitions: true },
  );
  interfaces = interfaces
    // Drop the placeholder root interface.
    .replace(/export interface GeneratedRoot \{[^}]*\}\n?/m, '')
    // Drop self-referential aliases produced for tsType-only enum defs.
    .replace(/(?:\/\*\*[\s\S]*?\*\/\n)?export type (\w+) = \1;\n?/g, '')
    // Drop the "referenced by GeneratedRoot" boilerplate unreachableDefinitions adds.
    .replace(/ \* This interface was referenced by `GeneratedRoot`'s JSON-Schema\n \* via the `definition` "[^"]*"\.\n/g, '')
    .replace(/\n \*\n \*\//g, '\n */')
    .replace(/\/\*\*\n \*\/\n/g, '')
    .trim();

  const enums = Object.entries(enumDefs).map(([name, schema]) => {
    // Derived member names can collide ('group@' and 'GROUP' -> Group);
    // fall back to the quoted raw value. x-enum-varnames from middleware
    // would make this exact.
    const used = new Set<string>();
    const members = (schema.enum ?? []).map((v) => {
      let member = memberName(v);
      if (used.has(member)) member = quote(v);
      used.add(member);
      return `  ${member}: ${literal(v)},`;
    }).join('\n');
    return `${tsdoc([schema.description], '')}export const ${name} = {\n${members}\n} as const;\nexport type ${name} = (typeof ${name})[keyof typeof ${name}];`;
  });

  const aliases = Object.entries(aliasDefs).map(([name, schema]) => (
    `${tsdoc([schema.description], '')}export type ${name} = ${tsExpr(schema)};`
  ));

  const importsBlock = referencedExternal.length
    ? `${groupedImports(referencedExternal, externals, './api-types')}\n`
    : '';
  const parts = [...enums, ...aliases, interfaces].filter(Boolean);
  if (parts.length === 0) {
    // A version that declares nothing (pure re-export delta) must still be a module.
    parts.push('/** This version declares no types of its own — see the version index for inherited re-exports. */\nexport {};');
  }
  return `${HEADER}\n${importsBlock}${parts.join('\n\n')}\n`;
}

/** One `'method.name': { params; response }` entry. Exported so generate.mts can compute cross-version base eligibility on the exact emitted text. */
export function directoryEntry(method: MethodModel): string {
  // Positional params: one can only be omitted if everything after it can be
  // too (Python allows defaulted-before-required; TS tuples don't, and
  // JSON-RPC positional semantics agree with TS here).
  const lastRequired = method.params.findLastIndex((p) => !p.optional);
  const params = method.params.map((p, i) => {
    const label = toIdentifier(p.name);
    return `${label}${p.optional && i > lastRequired ? '?' : ''}: ${tsExpr(p.schema)}`;
  });
  return `${methodDoc(method)}  ${quote(method.name)}: {\n    params: [${params.join(', ')}];\n    response: ${tsExpr(method.returns)};\n  };`;
}

function collectRefs(node: unknown, into: Set<string>): Set<string> {
  if (Array.isArray(node)) {
    node.forEach((n) => collectRefs(n, into));
  } else if (node !== null && typeof node === 'object') {
    const record = node as Record<string, unknown>;
    if (typeof record['$ref'] === 'string') into.add(refName(record['$ref']));
    Object.values(record).forEach((v) => collectRefs(v, into));
  }
  return into;
}

function importLine(nodes: unknown, externals: Externals = new Map(), localPath = './api-types'): string {
  const names = [...collectRefs(nodes, new Set())].sort();
  const out = groupedImports(names, externals, localPath);
  return out ? `${out}\n` : '';
}

/** Import for the query-grammar generics actually used in the emitted entries. */
function queryImportLine(entries: string, queryPath: string): string {
  const used = QUERY_TYPE_NAMES.filter((n) => entries.includes(`${n}<`));
  return used.length
    ? `import type {\n${used.map((n) => `  ${n},`).join('\n')}\n} from '${queryPath}';\n\n`
    : '';
}

/** `'event.name': { added; changed; … }` entry; exported for base-eligibility computation. */
export function eventEntry(event: EventModel): string {
  const variants = Object.entries(event.models)
    .map(([variant, schema]) => {
      // Model keys are ADDED/CHANGED/REMOVED, plus 'Subscription parameters'
      // for dynamic event sources — normalize to identifier-safe camelCase.
      const key = variant === 'Subscription parameters' ? 'subscriptionParams' : variant.toLowerCase();
      return `    ${isIdentifier(key) ? key : quote(key)}: ${tsExpr(schema)};`;
    })
    .join('\n');
  return `${tsdoc([event.doc, event.roles.length ? `@roles ${event.roles.join(', ')}` : null])}  ${quote(event.name)}: {\n${variants}\n  };`;
}

/**
 * Chain link for a non-root version's directory: where the previous version's
 * interface lives and which of its entries were removed in this version.
 * Entries *changed* in this version are re-declared in the delta interface
 * and displaced from the previous surface via `keyof` the delta.
 */
export interface DirectoryChainLink {
  /** Module path of the previous version's directory file. */
  prevPath: string;
  /** Entries present in the previous version but absent from this one. */
  removed: string[];
}

function chainedDirectory(
  interfaceName: string,
  entries: string,
  imports: string,
  link: DirectoryChainLink | undefined,
): string {
  if (!link) {
    return `${HEADER}\n${imports}export interface ${interfaceName} {\n${entries}\n}\n`;
  }
  const prevAlias = `Previous${interfaceName}`;
  const prevImport = `import type { ${interfaceName} as ${prevAlias} } from '${link.prevPath}';\n`;
  const removedUnion = link.removed.map((n) => `'${n}'`).join(' | ');
  if (!entries) {
    if (link.removed.length === 0) {
      return `${HEADER}\n${prevImport}\n/** Identical to the previous version's surface. */\nexport type ${interfaceName} = ${prevAlias};\n`;
    }
    return `${HEADER}\n${prevImport}\n/** The previous version's surface, without entries removed in this version. */\nexport type ${interfaceName} = Omit<${prevAlias}, ${removedUnion}>;\n`;
  }
  const deltaName = `${interfaceName}Delta`;
  const omitted = link.removed.length ? `keyof ${deltaName} | ${removedUnion}` : `keyof ${deltaName}`;
  return `${HEADER}\n${prevImport}${imports ? `\n${imports}` : '\n'}/** Entries added or changed in this version (directly, or through a referenced type). */\nexport interface ${deltaName} {\n${entries}\n}\n\n/** This version's surface: the previous version's, updated by the delta. */\nexport type ${interfaceName} = Omit<${prevAlias}, ${omitted}> & ${deltaName};\n`;
}

export function emitCallDirectory(ownMethods: MethodModel[], externals?: Externals, queryPath = '../shared/query-types', link?: DirectoryChainLink): string {
  const calls = ownMethods.filter((m) => !m.job);
  const entries = calls.map(directoryEntry).join('\n\n');
  return chainedDirectory('ApiCallDirectory', entries,
    queryImportLine(entries, queryPath) + importLine(calls, externals), link);
}

export function emitJobDirectory(ownMethods: MethodModel[], externals?: Externals, queryPath = '../shared/query-types', link?: DirectoryChainLink): string {
  const jobs = ownMethods.filter((m) => m.job);
  if (jobs.length === 0 && !link) {
    return `${HEADER}\n/** No job methods in the generated API slice. */\n// eslint-disable-next-line @typescript-eslint/no-empty-object-type\nexport interface ApiJobDirectory {\n}\n`;
  }
  const entries = jobs.map(directoryEntry).join('\n\n');
  return chainedDirectory('ApiJobDirectory', entries,
    queryImportLine(entries, queryPath) + importLine(jobs, externals), link);
}

export function emitEventDirectory(ownEvents: EventModel[], externals?: Externals, link?: DirectoryChainLink): string {
  const entries = ownEvents.map(eventEntry).join('\n\n');
  return chainedDirectory('ApiEventDirectory', entries, importLine(ownEvents, externals), link);
}

/**
 * A base directory in shared/: the entries stable across every generated
 * version, expressed as a Pick from the chain root's directory (where each of
 * those entries is materialized) — no entry duplication.
 */
export function emitDirectoryBase(interfaceName: string, sourceInterface: string, sourcePath: string, names: string[]): string {
  if (names.length === 0) {
    return `${HEADER}\n/** Nothing is stable across every generated version. */\n// eslint-disable-next-line @typescript-eslint/no-empty-object-type\nexport interface ${interfaceName} {\n}\n`;
  }
  const source = `Source${sourceInterface}`;
  const union = names.sort().map((n) => `  | '${n}'`).join('\n');
  return `${HEADER}\nimport type { ${sourceInterface} as ${source} } from '${sourcePath}';\n\n/** The entries whose signature (and referenced types) are identical in every generated version. */\nexport type ${interfaceName} = Pick<\n  ${source},\n${union}\n>;\n`;
}

export interface InheritedGroup {
  /** Module path of the ancestor's api-types, relative to this index. */
  path: string;
  enums: string[];
  types: string[];
}

export interface IndexOptions {
  inherited?: InheritedGroup[];
  queryPath?: string;
}

/**
 * Per-version index: re-exports the names inherited from ancestor versions
 * (so every version module presents its complete API surface regardless of
 * where a type is declared), the version's own types, the three directories,
 * and an `ApiDirectory` bundle for single-generic client binding.
 */
export function emitIndex({ inherited = [], queryPath = '../shared/query-types' }: IndexOptions = {}): string {
  const parts = [HEADER];
  parts.push(`import type { ApiCallDirectory } from './api-call-directory';
import type { ApiEventDirectory } from './api-event-directory';
import type { ApiJobDirectory } from './api-job-directory';`);
  parts.push(`export type {\n${QUERY_TYPE_NAMES.map((n) => `  ${n},`).join('\n')}\n} from '${queryPath}';`);
  for (const group of inherited) {
    if (group.enums.length) {
      parts.push(`export {\n${group.enums.map((n) => `  ${n},`).join('\n')}\n} from '${group.path}';`);
    }
    if (group.types.length) {
      parts.push(`export type {\n${group.types.map((n) => `  ${n},`).join('\n')}\n} from '${group.path}';`);
    }
  }
  parts.push(`export * from './api-types';
export type { ApiCallDirectory } from './api-call-directory';
export type { ApiJobDirectory } from './api-job-directory';
export type { ApiEventDirectory } from './api-event-directory';

/** The complete typed surface of this API version. */
export interface ApiDirectory {
  call: ApiCallDirectory;
  job: ApiJobDirectory;
  event: ApiEventDirectory;
}`);
  return `${parts.join('\n\n')}\n`;
}

export interface ManifestRow {
  name: string;
  kind: 'call' | 'job' | 'event' | 'type';
  /** Versions in which this entry is declared — pre-formatted tokens, optionally labeled with the change reason. */
  declaredIn: string[];
  /** Versions in which this entry disappears from the surface. */
  removedIn: string[];
}

/**
 * A greppable per-method history: the chain declares an entry only where it
 * changes, so `grep <method> src/generated/` alone cannot distinguish
 * "unchanged since vX" from "absent after vX" — this manifest can.
 */
export function emitManifest(rows: ManifestRow[], versions: string[]): string {
  const table = (subset: ManifestRow[]): string => subset
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((row) => {
      const [introduced, ...changed] = row.declaredIn;
      const parts = [`introduced ${introduced}`];
      if (changed.length) parts.push(`changed ${changed.join(', ')}`);
      if (row.removedIn.length) parts.push(`removed ${row.removedIn.join(', ')}`);
      return `| ${row.name} | ${row.kind} | ${parts.join('; ')} |`;
    })
    .join('\n');
  const surface = rows.filter((r) => r.kind !== 'type');
  const types = rows.filter((r) => r.kind === 'type');
  return `<!--
AUTO-GENERATED FILE — DO NOT EDIT.
Generated by scripts/generate-api-interface from a \`middlewared --dump-api\` dump.
-->

# API surface manifest

Versions: ${versions.join(', ')}.

Everything is declared in the version where it first appeared or changed;
between those versions it is inherited unchanged through the chain — so
absence from a version directory's text does NOT mean absence from that
version's surface. This manifest is the greppable record: an entry exists in
every version from its introduction until (if ever) listed as removed.
Changes are labeled "(docs)" when only documentation changed and "(via
referenced types)" when the entry itself is identical but a type it references
was re-declared; unlabeled changes are structural.

## Methods and events

| Name | Kind | History |
|------|------|---------|
${table(surface)}

## Types

| Name | Kind | History |
|------|------|---------|
${table(types)}
`;
}

/**
 * Root index for multi-version output: version namespaces, version-suffixed
 * aliases of the directory entry points (so multi-version consumers never
 * need import aliases), and the version registry — the compile-time bridge
 * between runtime version strings and directory types that the client
 * factory binds against.
 */
export function emitRootIndex(versions: string[]): string {
  const entries = versions.map((version) => {
    const dir = version.replaceAll('.', '_');
    return { version, dir, suffix: dir.replace(/^v/, 'V') };
  });
  const namespaces = entries
    .map(({ dir }) => `export * as ${dir} from './${dir}';`)
    .join('\n');
  const bundleImports = entries
    .map(({ dir, suffix }) => `import type { ApiDirectory as ApiDirectory${suffix} } from './${dir}';`)
    .join('\n');
  const aliases = entries.map(({ dir, suffix }) => `export type {
  ApiCallDirectory as ApiCallDirectory${suffix},
  ApiJobDirectory as ApiJobDirectory${suffix},
  ApiEventDirectory as ApiEventDirectory${suffix},
} from './${dir}';`).join('\n');
  const bundleExports = `export type {\n${entries.map(({ suffix }) => `  ApiDirectory${suffix},`).join('\n')}\n};`;
  const registry = `/** Runtime version string -> that version's complete typed API surface. */
export interface ApiDirectoryByVersion {
${entries.map(({ version, suffix }) => `  '${version}': ApiDirectory${suffix};`).join('\n')}
}

/** Every API version this package ships types for. */
export type SupportedApiVersion = keyof ApiDirectoryByVersion;

/** Runtime twin of {@link SupportedApiVersion}, ascending (oldest first). */
export const SUPPORTED_API_VERSIONS = [
${entries.map(({ version }) => `  '${version}',`).join('\n')}
] as const satisfies readonly SupportedApiVersion[];`;
  return `${HEADER}\n${bundleImports}\n\n${namespaces}\n\n${aliases}\n${bundleExports}\n\n${registry}\n`;
}
