/**
 * Emitters: turn the preprocessed API model into TypeScript source files.
 *
 * - Named object schemas -> interfaces via json-schema-to-typescript
 * - Named enum schemas   -> const-object + literal-union pairs (not TS enums:
 *   structural typing, erasableSyntaxOnly-safe, runtime-iterable)
 * - Method/event surface -> ApiCallDirectory / ApiJobDirectory / ApiEventDirectory
 */
import { compile } from 'json-schema-to-typescript';

import type { DefSchema, EventModel, MethodModel, Schema } from './types.mts';

type CompileInput = Parameters<typeof compile>[0];

const HEADER = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-api-interface from a \`middlewared --dump-api\` dump.
 */
`;

const refName = (ref: string): string => ref.replace('#/definitions/', '');

const isIdentifier = (s: string): boolean => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);

const toIdentifier = (s: string): string => {
  const cleaned = s.replace(/[^A-Za-z0-9_$]+/g, '_');
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
};

const quote = (value: unknown): string => `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const literal = (value: unknown): string => (typeof value === 'string' ? quote(value) : JSON.stringify(value));

/** Enum member name from a value: 'ACTIVE DIRECTORY' -> ActiveDirectory. */
function memberName(value: unknown): string {
  const name = String(value)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((t) => (t === t.toUpperCase() ? t.toLowerCase() : t))
    .map((t) => t[0].toUpperCase() + t.slice(1))
    .join('');
  return name && isIdentifier(name) ? name : quote(value);
}

/** Shallow JSON Schema -> TypeScript type expression (refs resolve to def names). */
export function tsExpr(schema: Schema | boolean | undefined | null): string {
  if (schema === true || schema === false || schema === undefined || schema === null) return 'unknown';
  if (schema.$ref) return refName(schema.$ref);
  if ('const' in schema) return literal(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map(literal).join(' | ');

  const variants = schema.anyOf ?? schema.oneOf;
  if (variants) {
    const parts = [...new Set(variants.map(tsExpr))];
    return parts.join(' | ');
  }
  if (schema.allOf?.length === 1) return tsExpr(schema.allOf[0]);

  if (Array.isArray(schema.type)) {
    return schema.type.map((t) => tsExpr({ ...schema, type: t })).join(' | ');
  }
  switch (schema.type) {
    case 'string': return 'string';
    case 'integer':
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'null': return 'null';
    case 'array': {
      if (schema.prefixItems && schema.items === false) {
        return `[${schema.prefixItems.map(tsExpr).join(', ')}]`;
      }
      const item = schema.items ? tsExpr(schema.items) : 'unknown';
      return /[|&\s]/.test(item) ? `(${item})[]` : `${item}[]`;
    }
    case 'object': {
      const props = schema.properties ?? {};
      const keys = Object.keys(props);
      if (keys.length === 0) {
        const patterns = Object.values(schema.patternProperties ?? {});
        if (patterns.length > 0) {
          return `Record<string, ${[...new Set(patterns.map(tsExpr))].join(' | ')}>`;
        }
        if (schema.additionalProperties === false) return 'Record<string, never>';
        if (typeof schema.additionalProperties === 'object' && schema.additionalProperties !== null) {
          return `Record<string, ${tsExpr(schema.additionalProperties)}>`;
        }
        return 'Record<string, unknown>';
      }
      const required = new Set(schema.required ?? []);
      const fields = keys.map((k) => {
        const key = isIdentifier(k) ? k : quote(k);
        return `${key}${required.has(k) ? '' : '?'}: ${tsExpr(props[k])}`;
      });
      return `{ ${fields.join('; ')} }`;
    }
    default: return 'unknown';
  }
}

function tsdoc(lines: (string | null | undefined)[], indent = '  '): string {
  const content = lines.filter(Boolean).flatMap((l) => String(l).split('\n'));
  if (content.length === 0) return '';
  return `${indent}/**\n${content.map((l) => `${indent} * ${l}`.trimEnd()).join('\n')}\n${indent} */\n`;
}

function methodDoc(method: MethodModel): string {
  return tsdoc([
    method.doc,
    method.roles.length ? `@roles ${method.roles.join(', ')}` : null,
    method.removedIn ? `@deprecated Removed in API version ${method.removedIn}.` : null,
  ]);
}

/**
 * Pydantic stamps a `title` on every field, and json-schema-to-typescript
 * hoists every titled subschema into a standalone named alias (Id1, Title2, …).
 * Titles are only meaningful as def names, so strip them everywhere below the
 * def root.
 */
function stripNestedTitles(node: unknown, isRoot = true): unknown {
  if (Array.isArray(node)) return node.map((n) => stripNestedTitles(n, false));
  if (node === null || typeof node !== 'object') return node;
  const source = node as Schema;
  const out: Schema = {};
  for (const [key, value] of Object.entries(source)) {
    if (key === 'title' && !isRoot) continue;
    // A $ref with siblings makes json-schema-to-typescript clone the target
    // into a suffixed duplicate (Alert1); keep such refs bare instead.
    if (source.$ref && key !== '$ref') continue;
    out[key] = stripNestedTitles(value, false);
  }
  // Closed empty objects render as the banned `{}` type; match tsExpr().
  if (out.type === 'object' && !out.$ref
    && Object.keys(out.properties ?? {}).length === 0
    && out.additionalProperties === false) {
    return { ...(out.description && { description: out.description }), tsType: 'Record<string, never>' };
  }
  return out;
}

/** "Used by: user.create (params), …" doc line, capped so hub types stay readable. */
function usedByLine(usedBy: string[] | undefined, cap = 10): string | null {
  if (!usedBy?.length) return null;
  const shown = usedBy.slice(0, cap).join(', ');
  const extra = usedBy.length > cap ? ` … and ${usedBy.length - cap} more` : '';
  return `Used by: ${shown}${extra}`;
}

const SHARED_PATH = '../shared/api-types';

/**
 * api-types.ts: interfaces (via json-schema-to-typescript) + const-object
 * enums. `sharedNames` are types that live in shared/api-types.ts — they are
 * imported rather than declared, keeping version dirs free of duplication.
 */
export async function emitTypes(definitions: Record<string, DefSchema>, sharedNames = new Set<string>()): Promise<string> {
  const objectDefs: Record<string, Schema> = {};
  const enumDefs: Record<string, Schema> = {};
  for (const [name, def] of Object.entries(definitions)) {
    const { _kind, _usedBy, ...schema } = def;
    const usage = usedByLine(_usedBy);
    if (usage) {
      schema.description = schema.description ? `${schema.description}\n\n${usage}` : usage;
    }
    (_kind === 'enum' ? enumDefs : objectDefs)[name] = stripNestedTitles(schema) as Schema;
  }

  // Enum defs are emitted by us and shared defs are imported; hand
  // json-schema-to-typescript an opaque `tsType` for both so references
  // render as the bare name.
  const referencedShared = [...collectRefs(Object.values(objectDefs), new Set())]
    .filter((name) => sharedNames.has(name))
    .sort();
  const jstsDefinitions: Record<string, Schema> = {
    ...objectDefs,
    ...Object.fromEntries(Object.keys(enumDefs).map((name) => [name, { tsType: name }])),
    ...Object.fromEntries(referencedShared.map((name) => [name, { tsType: name }])),
  };

  const root: Schema = {
    title: 'GeneratedRoot', type: 'object', additionalProperties: false, properties: {}, definitions: jstsDefinitions,
  };
  let interfaces = await compile(
    root as CompileInput,
    'GeneratedRoot',
    // additionalProperties intentionally not defaulted to false: pydantic
    // models set it explicitly; bare `dict` fields should stay open records.
    { bannerComment: '', unreachableDefinitions: true },
  );
  interfaces = interfaces
    // Drop the placeholder root interface.
    .replace(/export interface GeneratedRoot \{[^}]*\}\n?/m, '')
    // Drop self-referential aliases produced for tsType-only enum defs.
    .replace(/(?:\/\*\*[\s\S]*?\*\/\n)?export type (\w+) = \1;\n?/g, '')
    // Drop the "referenced by GeneratedRoot" boilerplate unreachableDefinitions adds.
    .replace(/ \* This interface was referenced by `GeneratedRoot`'s JSON-Schema\n \* via the `definition` "[^"]*"\.\n/g, '')
    .replace(/\n \*\n \*\//g, '\n */')
    .replace(/\/\*\*\n \*\/\n/g, '')
    .trim();

  const enums = Object.entries(enumDefs).map(([name, schema]) => {
    // Derived member names can collide ('group@' and 'GROUP' -> Group);
    // fall back to the quoted raw value. x-enum-varnames from middleware
    // would make this exact.
    const used = new Set<string>();
    const members = (schema.enum ?? []).map((v) => {
      let member = memberName(v);
      if (used.has(member)) member = quote(v);
      used.add(member);
      return `  ${member}: ${literal(v)},`;
    }).join('\n');
    return `${tsdoc([schema.description], '')}export const ${name} = {\n${members}\n} as const;\nexport type ${name} = (typeof ${name})[keyof typeof ${name}];`;
  });

  const sharedImport = referencedShared.length
    ? `import type {\n${referencedShared.map((n) => `  ${n},`).join('\n')}\n} from '${SHARED_PATH}';\n\n`
    : '';
  return `${HEADER}\n${sharedImport}${[...enums, interfaces].join('\n\n')}\n`;
}

function directoryEntry(method: MethodModel): string {
  // Positional params: one can only be omitted if everything after it can be
  // too (Python allows defaulted-before-required; TS tuples don't, and
  // JSON-RPC positional semantics agree with TS here).
  const lastRequired = method.params.findLastIndex((p) => !p.optional);
  const params = method.params.map((p, i) => {
    const label = toIdentifier(p.name);
    return `${label}${p.optional && i > lastRequired ? '?' : ''}: ${tsExpr(p.schema)}`;
  });
  return `${methodDoc(method)}  ${quote(method.name)}: {\n    params: [${params.join(', ')}];\n    response: ${tsExpr(method.returns)};\n  };`;
}

function collectRefs(node: unknown, into: Set<string>): Set<string> {
  if (Array.isArray(node)) {
    node.forEach((n) => collectRefs(n, into));
  } else if (node !== null && typeof node === 'object') {
    const record = node as Record<string, unknown>;
    if (typeof record['$ref'] === 'string') into.add(refName(record['$ref']));
    Object.values(record).forEach((v) => collectRefs(v, into));
  }
  return into;
}

function importLine(nodes: unknown, sharedNames = new Set<string>()): string {
  const names = [...collectRefs(nodes, new Set())].sort();
  const block = (list: string[], from: string) => (list.length
    ? `import type {\n${list.map((n) => `  ${n},`).join('\n')}\n} from '${from}';\n`
    : '');
  const out = block(names.filter((n) => sharedNames.has(n)), SHARED_PATH)
    + block(names.filter((n) => !sharedNames.has(n)), './api-types');
  return out ? `${out}\n` : '';
}

export function emitCallDirectory(methods: MethodModel[], sharedNames?: Set<string>): string {
  const calls = methods.filter((m) => !m.job);
  const entries = calls.map(directoryEntry).join('\n\n');
  return `${HEADER}\n${importLine(calls, sharedNames)}export interface ApiCallDirectory {\n${entries}\n}\n`;
}

export function emitJobDirectory(methods: MethodModel[], sharedNames?: Set<string>): string {
  const jobs = methods.filter((m) => m.job);
  if (jobs.length === 0) {
    return `${HEADER}\n/** No job methods in the generated API slice. */\n// eslint-disable-next-line @typescript-eslint/no-empty-object-type\nexport interface ApiJobDirectory {\n}\n`;
  }
  const entries = jobs.map(directoryEntry).join('\n\n');
  return `${HEADER}\n${importLine(jobs, sharedNames)}export interface ApiJobDirectory {\n${entries}\n}\n`;
}

export function emitEventDirectory(events: EventModel[], sharedNames?: Set<string>): string {
  const entries = events.map((event) => {
    const variants = Object.entries(event.models)
      .map(([variant, schema]) => {
        // Model keys are ADDED/CHANGED/REMOVED, plus 'Subscription parameters'
        // for dynamic event sources — normalize to identifier-safe camelCase.
        const key = variant === 'Subscription parameters' ? 'subscriptionParams' : variant.toLowerCase();
        return `    ${isIdentifier(key) ? key : quote(key)}: ${tsExpr(schema)};`;
      })
      .join('\n');
    return `${tsdoc([event.doc, event.roles.length ? `@roles ${event.roles.join(', ')}` : null])}  ${quote(event.name)}: {\n${variants}\n  };`;
  }).join('\n\n');
  return `${HEADER}\n${importLine(events, sharedNames)}export interface ApiEventDirectory {\n${entries}\n}\n`;
}

export interface IndexOptions {
  sharedEnums?: string[];
  sharedTypes?: string[];
}

/**
 * Per-version index: re-exports the version's shared names (so every version
 * module presents its complete API surface regardless of where a type
 * physically lives), the version-local types, the three directories, and an
 * `ApiDirectory` bundle for single-generic client binding.
 */
export function emitIndex({ sharedEnums = [], sharedTypes = [] }: IndexOptions = {}): string {
  const parts = [HEADER];
  parts.push(`import type { ApiCallDirectory } from './api-call-directory';
import type { ApiEventDirectory } from './api-event-directory';
import type { ApiJobDirectory } from './api-job-directory';`);
  if (sharedEnums.length) {
    parts.push(`export {\n${sharedEnums.map((n) => `  ${n},`).join('\n')}\n} from '${SHARED_PATH}';`);
  }
  if (sharedTypes.length) {
    parts.push(`export type {\n${sharedTypes.map((n) => `  ${n},`).join('\n')}\n} from '${SHARED_PATH}';`);
  }
  parts.push(`export * from './api-types';
export type { ApiCallDirectory } from './api-call-directory';
export type { ApiJobDirectory } from './api-job-directory';
export type { ApiEventDirectory } from './api-event-directory';

/** The complete typed surface of this API version. */
export interface ApiDirectory {
  call: ApiCallDirectory;
  job: ApiJobDirectory;
  event: ApiEventDirectory;
}`);
  return `${parts.join('\n\n')}\n`;
}

/**
 * Root index for multi-version output: version namespaces plus
 * version-suffixed aliases of the directory entry points, so multi-version
 * consumers (TrueNAS Connect) never need import aliases.
 */
export function emitRootIndex(versionDirs: string[]): string {
  const namespaces = versionDirs
    .map((dir) => `export * as ${dir} from './${dir}';`)
    .join('\n');
  const aliases = versionDirs.map((dir) => {
    const suffix = dir.replace(/^v/, 'V');
    return `export type {
  ApiCallDirectory as ApiCallDirectory${suffix},
  ApiJobDirectory as ApiJobDirectory${suffix},
  ApiEventDirectory as ApiEventDirectory${suffix},
  ApiDirectory as ApiDirectory${suffix},
} from './${dir}';`;
  }).join('\n');
  return `${HEADER}\n${namespaces}\n\n${aliases}\n`;
}
