import { describe, expect, it } from 'vitest';
import { pythonRepr } from './fake-api-error';

/**
 * `pythonRepr` directly, rather than through `fakeApiError`.
 *
 * The categories below are awkward to carry in a `reason` — a lone surrogate
 * does not survive a round trip through most of the things that would read
 * one — and the point of these rows is the escaping rule rather than the
 * fixture around it. `fake-api-error.spec.ts` covers the rule as a caller
 * meets it; this covers the rule.
 *
 * Every expectation is CPython's own output, generated by running the input
 * through `python3 -c 'print(repr(…))'`.
 */
describe('pythonRepr', () => {
  it.each([
    ['a private-use character', 'pool \u{e000}', "'pool \\ue000'"],
    ['a line separator', 'line\u{2028}break', "'line\\u2028break'"],
    ['a paragraph separator', 'para\u{2029}break', "'para\\u2029break'"],
    ['a lone surrogate', 'bad\u{d800}name', "'bad\\ud800name'"],
  ])('escapes %s', (_label, value, expected) => {
    expect(pythonRepr(value)).toBe(expected);
  });

  it('leaves an ordinary string alone but for its quotes', () => {
    expect(pythonRepr('Dataset is locked')).toBe("'Dataset is locked'");
  });

  it('treats U+0020 as printable, alone among the separators', () => {
    expect(pythonRepr('a b')).toBe("'a b'");
  });
});
