/**
 * A known gap we ship: `app.query`'s call side (`AppEntry`) is narrower than
 * its event side (`AppEntryInput`, which has `ERROR`, `error_reason` and a
 * nullable `version`). The event side matches the appliance.
 *
 * These assertions **fail when the gap closes** — nothing else would notice.
 * When a version's block fails, check its call and event sides now agree
 * (a regeneration once moved the gap rather than closing it), then delete
 * that block only. v27 is pinned because `yarn generate:api` rewrites it;
 * v28 already agrees and is the target shape.
 */
import { describe, expectTypeOf, it } from 'vitest';

import type {
  ApiDirectoryV27_0_0,
  ApiDirectoryV28_0_0,
  v25_10_0,
  v27_0_0,
  v28_0_0,
} from '@/generated';

describe('known gap: app events disagree with app calls', () => {
  /**
   * Both shapes are homed in `v25_10_0/` and the directory is frozen again, so
   * closing this means either hand-maintenance there or another unfreeze — and
   * an unfreeze deletes the entries no dump describes — seven commits of
   * TNC-2283, `dd715de`..`f08de91`, went on putting them back.
   */
  describe('v25.10.0 — frozen, closes only by hand', () => {
    type EventFields = v25_10_0.ApiEventDirectory['app.query']['added']['fields'];

    it('still types the call-side version as non-nullable', () => {
      expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
      expectTypeOf<v25_10_0.AppEntry['version']>().toEqualTypeOf<string>();
    });

    it('still omits ERROR from the call-side state', () => {
      type EventHasError = 'ERROR' extends EventFields['state'] ? true : false;
      expectTypeOf<EventHasError>().toEqualTypeOf<true>();
      type CallHasError = 'ERROR' extends v25_10_0.AppEntry['state'] ? true : false;
      expectTypeOf<CallHasError>().toEqualTypeOf<false>();
    });
  });

  /**
   * The reachable one. `v27_0_0` is regenerated by any ordinary run, so this
   * closes the day middleware widens v27's `AppEntry` — or the day v27 starts
   * declaring its own `app.query` event rather than inheriting the root's.
   */
  describe('v27.0.0 — regenerated, inherits the widened event', () => {
    type EventFields = v27_0_0.ApiEventDirectory['app.query']['added']['fields'];

    it('still types the call-side version as non-nullable', () => {
      expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
      expectTypeOf<v27_0_0.AppEntry['version']>().toEqualTypeOf<string>();
    });

    it('still omits ERROR from the call-side state', () => {
      type EventHasError = 'ERROR' extends EventFields['state'] ? true : false;
      expectTypeOf<EventHasError>().toEqualTypeOf<true>();
      type CallHasError = 'ERROR' extends v27_0_0.AppEntry['state'] ? true : false;
      expectTypeOf<CallHasError>().toEqualTypeOf<false>();
    });
  });

  /**
   * Not a gap — asserted so that a regression *into* one is caught. If a later
   * dump narrows v28's `AppEntry` the way v27's still is, this fails and says
   * the disagreement has spread rather than letting it arrive unremarked.
   */
  it('v28.0.0 agrees with itself', () => {
    type EventFields = v28_0_0.ApiEventDirectory['app.query']['added']['fields'];
    expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
    expectTypeOf<v28_0_0.AppEntry['version']>().toEqualTypeOf<string | null>();
    type CallHasError = 'ERROR' extends v28_0_0.AppEntry['state'] ? true : false;
    expectTypeOf<CallHasError>().toEqualTypeOf<true>();
  });
});



/**
 * A second known gap: ten methods the dump marks `removed_in` are still
 * declared at the versions that removed them.
 *
 * `preprocess.mts` puts `removed_in` on `MethodModel.removedIn` and nothing
 * reads it. `_create_api` makes a removed method *private*, so a v27 appliance
 * already refuses `service.start` while this package types it as callable
 * (`b755b2b:plugins/service/__init__.py:255`, `main.py:493-495`). Eleven carry
 * the marker; `pool.ddt_prefetch` is already absent for an unrelated reason,
 * and `service.*` moved to the call directory at v27 rather than leaving.
 *
 * These **fail when the gap closes**. Delete the ones that close.
 */
describe('known gap: removed_in is carried and not enforced', () => {
  /** Gone at v27 upstream; still declared at v27 and at v28. */
  it('keeps the v27 removals callable', () => {
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('pool.is_upgraded');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('system.feature_enabled');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('service.start');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('service.stop');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('service.restart');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('service.reload');

    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('service.start');
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('pool.is_upgraded');
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('system.feature_enabled');
  });

  /** Gone at v28 upstream; still declared at v28. */
  it('keeps the v28 removals callable', () => {
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('auth.login');
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('auth.login_with_api_key');
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty('system.product_type');
    expectTypeOf<ApiDirectoryV28_0_0['call']>().toHaveProperty(
      'system.advanced.syslog_certificate_authority_choices'
    );
  });
});


/**
 * A third known gap: at v27, `interface.query`'s event payload contradicts its
 * call side.
 *
 * `4303dc820b` documented `stp`, `xmit_hash_policy` and `lacpdu_rate` and
 * dropped `extra = "allow"` in `api/v28_0_0/interface.py` alone. Every slice's
 * events carry the running tree's models, so v27's event payload took the v28
 * shape while v27's own `InterfaceEntry` kept the open one — and a v27
 * appliance still sends keys the closed shape does not admit.
 *
 * Not hand-corrected like `pool.dataset.query`: that lives in a frozen file
 * and v27 is rewritten by every run. These **fail when the gap closes**.
 */
describe('known gap: v27 interface events disagree with interface calls', () => {
  it('keeps the call side open', () => {
    expectTypeOf<v27_0_0.InterfaceEntry>().toHaveProperty('failover_group');
    expectTypeOf<v27_0_0.InterfaceEntry['anything else']>().toEqualTypeOf<unknown>();
  });

  it('still types the event payload as closed, with the v28 fields', () => {
    expectTypeOf<v27_0_0.InterfaceEntryInput>().toHaveProperty('stp');
    expectTypeOf<v27_0_0.InterfaceEntryInput>().toHaveProperty('xmit_hash_policy');
    expectTypeOf<v27_0_0.InterfaceEntryInput>().toHaveProperty('lacpdu_rate');
  });

  it('is what the event arms carry', () => {
    expectTypeOf<
      v27_0_0.ApiEventDirectory['interface.query']['added']['fields']
    >().toEqualTypeOf<v27_0_0.InterfaceEntryInput>();
  });
});
