/**
 * A known gap we ship: `app.query`'s call side (`AppEntry`) is narrower than
 * its event side (`AppEntryInput`, which has `ERROR`, `error_reason` and a
 * nullable `version`). The event side matches the appliance.
 *
 * These assertions **fail when the gap closes** — nothing else would notice.
 * When a version's block fails, check its call and event sides now agree
 * (a regeneration once moved the gap rather than closing it), then delete
 * that block only. v26 is pinned because `yarn generate:api` rewrites it;
 * v27 already agrees and is the target shape.
 */
import { describe, expectTypeOf, it } from 'vitest';

import type {
  ApiDirectoryV26_0_0,
  ApiDirectoryV27_0_0,
  v25_10_0,
  v26_0_0,
  v27_0_0,
} from '@/generated';

describe('known gap: app events disagree with app calls', () => {
  /**
   * Both shapes are homed in `v25_10_0/` and the directory is frozen again, so
   * closing this means either hand-maintenance there or another unfreeze — and
   * an unfreeze deletes the entries no dump describes — seven commits of
   * TNC-2283, `dd715de`..`f08de91`, went on putting them back.
   */
  describe('v25.10.0 — frozen, closes only by hand', () => {
    type EventFields = v25_10_0.ApiEventDirectory['app.query']['added']['fields'];

    it('still types the call-side version as non-nullable', () => {
      expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
      expectTypeOf<v25_10_0.AppEntry['version']>().toEqualTypeOf<string>();
    });

    it('still omits ERROR from the call-side state', () => {
      type EventHasError = 'ERROR' extends EventFields['state'] ? true : false;
      expectTypeOf<EventHasError>().toEqualTypeOf<true>();
      type CallHasError = 'ERROR' extends v25_10_0.AppEntry['state'] ? true : false;
      expectTypeOf<CallHasError>().toEqualTypeOf<false>();
    });
  });

  /**
   * The reachable one. `v26_0_0` is regenerated by any ordinary run, so this
   * closes the day middleware widens v26's `AppEntry` — or the day v26 starts
   * declaring its own `app.query` event rather than inheriting the root's.
   */
  describe('v26.0.0 — regenerated, inherits the widened event', () => {
    type EventFields = v26_0_0.ApiEventDirectory['app.query']['added']['fields'];

    it('still types the call-side version as non-nullable', () => {
      expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
      expectTypeOf<v26_0_0.AppEntry['version']>().toEqualTypeOf<string>();
    });

    it('still omits ERROR from the call-side state', () => {
      type EventHasError = 'ERROR' extends EventFields['state'] ? true : false;
      expectTypeOf<EventHasError>().toEqualTypeOf<true>();
      type CallHasError = 'ERROR' extends v26_0_0.AppEntry['state'] ? true : false;
      expectTypeOf<CallHasError>().toEqualTypeOf<false>();
    });
  });

  /**
   * Not a gap — asserted so that a regression *into* one is caught. If a later
   * dump narrows v27's `AppEntry` the way v26's still is, this fails and says
   * the disagreement has spread rather than letting it arrive unremarked.
   */
  it('v27.0.0 agrees with itself', () => {
    type EventFields = v27_0_0.ApiEventDirectory['app.query']['added']['fields'];
    expectTypeOf<EventFields['version']>().toEqualTypeOf<string | null>();
    expectTypeOf<v27_0_0.AppEntry['version']>().toEqualTypeOf<string | null>();
    type CallHasError = 'ERROR' extends v27_0_0.AppEntry['state'] ? true : false;
    expectTypeOf<CallHasError>().toEqualTypeOf<true>();
  });
});



/**
 * A second known gap: ten methods the dump marks `removed_in` are still
 * declared at the versions that removed them.
 *
 * `preprocess.mts` puts `removed_in` on `MethodModel.removedIn` and nothing
 * reads it. `_create_api` makes a removed method *private*, so a v26 appliance
 * already refuses `service.start` while this package types it as callable
 * (`b755b2b:plugins/service/__init__.py:255`, `main.py:493-495`). Eleven carry
 * the marker; `pool.ddt_prefetch` is already absent for an unrelated reason,
 * and `service.*` moved to the call directory at v26 rather than leaving.
 *
 * These **fail when the gap closes**. Delete the ones that close.
 */
describe('known gap: removed_in is carried and not enforced', () => {
  /** Gone at v26 upstream; still declared at v26 and at v27. */
  it('keeps the v26 removals callable', () => {
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('pool.is_upgraded');
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('system.feature_enabled');
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('service.start');
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('service.stop');
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('service.restart');
    expectTypeOf<ApiDirectoryV26_0_0['call']>().toHaveProperty('service.reload');

    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('service.start');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('pool.is_upgraded');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('system.feature_enabled');
  });

  /** Gone at v27 upstream; still declared at v27. */
  it('keeps the v27 removals callable', () => {
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('auth.login');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('auth.login_with_api_key');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty('system.product_type');
    expectTypeOf<ApiDirectoryV27_0_0['call']>().toHaveProperty(
      'system.advanced.syslog_certificate_authority_choices'
    );
  });
});
